name: kuraken
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  animated_text_kit: ^3.1.0
  cloud_firestore: ^0.16.0
  cupertino_icons: ^1.0.0
  firebase_auth: ^0.20.0+1
  firebase_core: ^0.7.0
  flutter:
    sdk: flutter
  flutter_auth_buttons: ^0.10.0
  flutter_dotenv: ^3.1.0
  flutter_hooks: ^0.15.0
  flutter_state_notifier: ^0.6.1
  freezed: ^0.12.7
  hooks_riverpod: ^0.12.3+1
  json_annotation: ^3.1.1
  json_serializable: ^3.5.1
  pedantic: ^1.9.2
  pedantic_mono: any
  shared_preferences: ^0.5.12+4
  tuple: ^1.0.3
  twitter_login: ^2.1.3

dev_dependencies:
  build_runner: ^1.11.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - .env
  #  - images/*

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages


  fonts:
    - family: Emblema One
      fonts:
      - asset: fonts/EmblemaOne-Regular.ttf

